version: '3'
services:
  mysql:
    # restart: always
    image: mysql:5.7.16
    container_name: mysql_base
    # volumes:
    # - ./mydir:/mydir
    # - ./datadir:/var/lib/mysql
    # - ./conf/my.cnf:/etc/my.cnf
    #      数据库还原目录 可将需要还原的sql文件放在这里
    # - /docker/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=server"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
    restart: no
