version: "3"

networks:
  app-tier:
    driver: bridge

services:

  minio:
    image: bitnami/minio:2023.11.20
    restart: always
    volumes:
      - ./minio/data:/bitnami/minio/data
    ports:
      - 9010:9000
      - 9011:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123.

    # networks:
    #   - app-tier

    # myapp:
    #   image: "YOUR_APPLICATION_IMAGE"
    #   networks:
    #     - app-tier
    #   environment:
    #     - MINIO_SERVER_ACCESS_KEY=minio-access-key
    #     - MINIO_SERVER_SECRET_KEY=minio-secret-key
