services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pgsql
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
