services:
  vsftpd:
    image: fauria/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      FTP_USER: user
      FTP_PASS: 123456
      PASV_ADDRESS: 127.0.0.1  # 替换为实际的主机IP
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
      PASV_ENABLE: YES
      PASV_ADDRESS_RESOLVE: NO
    volumes:
      - ./data/ftp/user:/home/vsftpd/user

  sftp:
    image: atmoz/sftp
    ports:
      - "2222:22"  # 将容器的22端口映射到主机的2222端口
    environment:
      SFTP_USERS: user:123456:1001  # 用户名:密码:UID
    volumes:
      - ./data/sftp/user:/home/user  # 挂载本地目录到容器内的用户主目录