version: "3"
services:
  redis:
    image: redis
    restart: always
    volumes:
      - ./data/redis_data:/data
    ports:
      - 6379:6379

  redisinsight:
    image: "redis/redisinsight:latest"
    ports:
      - "5540:5540"
    volumes:
      - "./data/redisinsight:/data"
