GET http://127.0.0.1:8080/server/state

### 
# 分割符号

GET http://127.0.0.1:8080/med/server/token
###

###
# post - json 
POST http://127.0.0.1:8080/phone/checkout
Content-Type: application/json
{
    "verifycode": "8848",
    "phone_num": "13788488848"
}
