### vscode下测试http常用请求的方式
### 注释
### http测试工具
GET http://127.0.0.1:8080/server/state

### 
# 分割符号

GET http://127.0.0.1:8080/med/server/token
###

# 注释使用 # 号
# 三个 # 号 隔离一个请求  ###
# 表达式以请求方式开头 如 GET POST 等 有自动联想功能
# 紧挨着是head部分
# 重点:head 部分不能加 " 直接 key: value
# body 和 head 部分之间必须隔开一行 不能放一起
# 配置不通的环境变量 需要 在 项目的 .vscode/.settings.json 文件中进行相关的配置

###
# post - json 
POST http://127.0.0.1:8080/phone/checkout
Content-Type: application/json

#中间必须空一行
{
    "verifycode": "8848",
    "phone_num": "13788488848"
}


## 定义变量
@hostname = 127.0.0.1
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

###

@name = hello

GET http://{{host}}/authors/{{name}} 

###

PATCH https://{{host}}/authors/{{name}} HTTP/1.1
Content-Type: {{contentType}}

{
    "content": "foo bar",
    "created_at": "{{createdAt}}",
    "modified_by": "{{modifiedBy}}"
}

### 
# post content-type = multipart/form-data 
# 注意 此处  boundary 分割字符串 postman 导出的 是错误的
# 因为分割符在使用时 需要 添加 '--' 
# 即 当 boundary=--a 时
# 使用时 ----a

POST https://api.example.com/user/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
